version: "3.8"

services:
  php:
    image: wordpress:php8.2-fpm
    container_name: phpwp
    working_dir: /var/www/html/wp
    volumes:
        - ./php-fpm/var/log/php-fpm:/var/log/php-fpm
        - ./var/www/html:/var/www/html
        - ./php-fpm/php.ini-development:/usr/local/etc/php/php.ini-development
        - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini-production
        - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    
    restart: unless-stopped
    
    networks:
      - wordpress

  mysql:
    image: mysql:latest
    container_name: mysqlwp
    volumes:
        - ./mysql/my.cnf:/etc/my.cnf
        - ./mysql/mysql_data:/var/lib/mysql
        
    environment:
        MYSQL_ROOT_PASSWORD: 147258369
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wp
        MYSQL_PASSWORD: 147258369
    restart: unless-stopped
       
    networks:
      - wordpress

  nginx:
    image: nginx:latest
    container_name: nginxwp
    working_dir: /var/www/html
    volumes:
        - ./var/www/html:/var/www/html
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 80:80
     - 443:443
     
    restart: unless-stopped
    
    networks:
      - wordpress

networks:
  wordpress:
    name: wp-network
    driver: bridge
